# Generated by Django 5.0.9 on 2024-11-29 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorsore', '0041_landingpage'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wagtailcore.page')),
            ],
        ),
    ]
